# Playbook to install & start httpd
#

---

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

  - name: 1. Install httpd
    yum: name=httpd state=present
  - name: 2. Start httpd service
    service: name=httpd state=started
