
---

- name: Include LAMP stack playbook
  import_playbook: lamp_stack.yml

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

    - name: Create database for joomla
      mysql_db:
            name: joomla_db
            config_file: /etc/my.cnf
            state: present
      tags: create_joomla_db
