
---

- name: Include LAMP stack playbook
  import_playbook: lamp_stack.yml

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

    - name: Create database for joomla
      mysql_db:
            name: joomla_db
            config_file: /etc/my.cnf
            state: present
      tags: create_joomla_db

    - name: Create mysql user for joomla
      mysql_user:
             name: dbuser
             password: Joomla@123#
             config_file: /etc/my.cnf
             priv: 'joomla_db.*:ALL'
             state: present
      tags: create_mysql_user

    - name: Install wget and unzip
      yum:
        name: ['wget','unzip']
      tags: install_wget_unzip

    - name: Download & extract Joomla file in /var/www/html
      unarchive:
          src: https://downloads.joomla.org/cms/joomla3/3-9-6/Joomla_3-9-6-Stable-Full_Package.zip
          dest: /var/www/html
          remote_src: yes
      tags: download_extract_joomla

    - name: Change Joomla directory permissions
      file:
        name: /var/www/html
        owner: apache
        group: apache
        mode: '755'
        recurse: yes
        state: directory
      tags: change_directory_permissions
