
---

- name: Include LAMP stack playbook
  import_playbook: lamp_stack.yml

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

    - name: Create database for joomla
      mysql_db:
            name: joomla_db
            config_file: /etc/my.cnf
            state: present
      tags: create_joomla_db

    - name: Create mysql user for joomla
      mysql_user:
             name: dbuser
             password: Joomla@123#
             config_file: /etc/my.cnf
             priv: 'joomla_db.*:ALL'
             state: present
      tags: create_mysql_user
