
---

- hosts: all
  user: ansadm
  roles:
     - webservers
     - database
  vars:
     - mysql_username: root
     - mysql_password: joomla
  become: yes
  become_method: sudo

  tasks:

     - name: Install apache
       yum: name=httpd state=present
       notify: start httpd
       tags: install_apache

     # Running the handler named 'start httpd' at this point only instead of the end of the playbook using below statement
     - meta: flush_handlers

     - name: Install mariadb
       yum: 
         name:
           - mariadb
           - mariadb-server
         state: present

       notify: start mariadb
       tags: install_mariadb

     - meta: flush_handlers

     - name: Install epel-release
       yum:
         name: epel-release
         state: present
       tags: install_epel_release

     - name: Install python2-pip
       yum:
        name: python2-pip
        state: present
       tags: install_python2-pip

     - name: Install PyMySQL python module
       pip:
        name: PyMySQL
       tags: install_pymysql

     - name: Reset mariadb root password
       mysql_user: name=root password={{ mysql_password }} config_file=/etc/my.cnf
       tags: reset_mariadb_password

     - name: Copy my.cnf to /etc location
       template: src=/home/ansadm/ansible_playbooks/template_files/my.cnf dest=/etc owner=mysql group=mysql
       notify: restart mariadb
       tags: copy_my_cnf

     - meta: flush_handlers

     # Install php 7
     
     - name: Install remi-release
       yum: 
         name: 
           - http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
         state: present
       tags: install_remi_release
    
     - name: Installing yum utils
       yum:
         name: 
           - yum-utils
         state: latest
       tags: install_yum_utils

     - name: Enable Remi repository for PHP7
       yum_repository:
             name: remi-php73
             description: Remi's PHP 7.3 RPM repository for Enterprise Linux 7 - $basearch
             mirrorlist: http://cdn.remirepo.net/enterprise/7/php73/mirror
             enabled: yes
             gpgcheck: yes
             gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi

       tags: enable_remi

     - name: Installing PHP 7
       yum:
         name:
           - php
           - php-mcrypt
           - php-cli
           - php-gd
           - php-curl
           - php-mysql
           - php-ldap
           - php-zip
           - php-fileinfo

         state: present
     
       notify: restart httpd
       tags: install_php_7
 
