
---

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

     - name: Install epel-release
       yum: 
         name: epel-release
         state: present
       tags: install_epel

