
--- 

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

  - name: 1. Install Apache (httpd)
    yum: name=httpd state=present
    tags: install_apache

  - name: 2. Start httpd service
    service: name=httpd state=started enabled=yes
    tags: start_httpd

  - name: 3. Install mariadb-server
    yum:
      name:
        - mariadb
        - mariadb-server
      state: present
    tags: install_mariadb_server

  - name: Start mariadb service
    service: name=mariadb state=started
    tags: start_mariadb

  - name: update mysql root password for all root accounts
    mysql_user: name=root host={{ item }} password=vlink config_file=/etc/my.cnf
    with_items:
        - "kubernetus"
        - 127.0.0.1
        - ::1
        - localhost
  
    tags: reset_root_password

  - name: Copying my.cnf file to /etc location
    template: src=/home/ansadm/ansible_playbooks/template_files/my.cnf dest=/etc owner=mysql group=mysql
    tags: copy_my_cnf

  - name: Restart mariadb service
    service: name=mariadb state=restarted
    tags: restart_mariadb

  # Install php 7

  - name: Install epel-release
    yum: name=epel-release state=present
    tags: install_epel
