
--- 

- hosts: all
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

  - name: 1. Install Apache (httpd)
    yum: name=httpd state=present
    tags: install_apache

  - name: 2. Start httpd service
    service: name=httpd state=started enabled=yes
    tags: start_httpd

